general.import = [
    "~/.config/alacritty/themes/themes/hatsunemiku.toml"
]


[window]
padding.y = 1
padding.x = 1

decorations = "Buttonless"

blur = true

option_as_alt = "Both"




[font]
normal.family = "hack nerd font"  # Using the mono version
size = 14  # Adjust as needed

[env]
TERM = "xterm-256color"
COLORTHEME = "truecolor"
